Repository himkt/konoha, pull requests merged in 2021-12, with the labels that each got.

#158 Remove `poetry-dynamic-versioning`
  pyproject.toml
Labels: dependencies

#159 Configurable sentence tokenizer
  README.md
  konoha/sentence_tokenizer.py
  tests/test_sentence_tokenizer.py
Labels: core feature

#160 Update importlib-metadata
  poetry.lock
  pyproject.toml
Labels: dependencies

#161 Add workflow to publish
  .github/workflows/publish.yml
Labels: other
