Repository himkt/konoha, pull requests merged in 2021-03, with the labels that each got.

#117 Run pre-compile regular expressions before tokenization
  konoha/sentence_tokenizer.py
Labels: core feature

#116 Support AllenNLP>=1.3.0 by renaming path to Token class
  konoha/integrations/allennlp.py
  poetry.lock
  pyproject.toml
  test_fixtures/classifier_v1.jsonnet
  tests/integrations/test_allennlp_integration.py
Labels: bug, integration

#118 Packaging/poetry dynamic versioning
  konoha/__init__.py
  poetry.lock
  pyproject.toml
Labels: other

#119 Update max-line-length for linters and remove poetry-dynamic-versioning.substitution
  pyproject.toml
  setup.cfg
Labels: other

#120 Update API module: change endpoint path and upgrade Ubuntu to 20.04
  .github/workflows/pythonpackage.yml
  README.md
  docker/app/Dockerfile
  konoha/api/server.py
  konoha/api/v1/tokenization.py
  libexec/api.py
  tests/api/v1/test_tokenization.py
Labels: api, other

#121 Update README to add description of breaking change
  README.md
Labels: documentation

#122 Update Dockerfile to reduce image size
  docker/app/Dockerfile
Labels: other

#123 Feature/remote tokenization
  konoha/api/v1/tokenization.py
  konoha/word_tokenizer.py
  poetry.lock
  pyproject.toml
  tests/word_tokenizer/test_remote_tokenizer.py
Labels: api, core feature

#124 chore: Fix typo in README
  README.md
Labels: documentation

#125 Cleanup Dockerfiles
  docker/app/Dockerfile
  docker/dev/Dockerfile
Labels: other
