Repository himkt/konoha, pull requests merged in 2021-06, with the labels that each got.

#140 Remove konoa.konoha_token
  konoha/konoha_token.py
  tests/api/v1/test_tokenization.py
  tests/test_token.py
  tests/test_word_tokenizer.py
Labels: core feature

#141 Remove `with_postag` from WordTokenizer
  data/model.knm
  example/tokenize_demo.py
  konoha/api/v1/batch_tokenization.py
  konoha/api/v1/tokenization.py
  konoha/data/token.py
  konoha/integrations/allennlp.py
  konoha/sentence_tokenizer.py
  konoha/word_tokenizer.py
  konoha/word_tokenizers/character_tokenizer.py
  konoha/word_tokenizers/janome_tokenizer.py
  konoha/word_tokenizers/kytea_tokenizer.py
  konoha/word_tokenizers/mecab_tokenizer.py
  konoha/word_tokenizers/nagisa_tokenizer.py
  konoha/word_tokenizers/sentencepiece_tokenizer.py
  konoha/word_tokenizers/sudachi_tokenizer.py
  test_fixtures/word_tokenizers/character.jsonl
  test_fixtures/word_tokenizers/janome.jsonl
  test_fixtures/word_tokenizers/janome/wakati.jsonl
  test_fixtures/word_tokenizers/kytea.jsonl
  test_fixtures/word_tokenizers/kytea/wakati.jsonl
  test_fixtures/word_tokenizers/mecab.jsonl
  test_fixtures/word_tokenizers/mecab/wakati.jsonl
  test_fixtures/word_tokenizers/nagisa.jsonl
  test_fixtures/word_tokenizers/nagisa/wakati.jsonl
  test_fixtures/word_tokenizers/sentencepiece.jsonl
  test_fixtures/word_tokenizers/sudachi.jsonl
  test_fixtures/word_tokenizers/sudachi/wakati.jsonl
  test_fixtures/word_tokenizers/whitespace.jsonl
  tests/api/v1/test_batch_tokenization.py
  tests/api/v1/test_tokenization.py
  tests/data/test_token.py
  tests/test_word_tokenizer.py
Labels: core feature

#142 Import libraries in initializers of tokenizer classes
  konoha/word_tokenizers/janome_tokenizer.py
  konoha/word_tokenizers/kytea_tokenizer.py
  konoha/word_tokenizers/mecab_tokenizer.py
  konoha/word_tokenizers/nagisa_tokenizer.py
  konoha/word_tokenizers/sentencepiece_tokenizer.py
  konoha/word_tokenizers/sudachi_tokenizer.py
  tests/api/v1/test_tokenization.py
Labels: other

#143 Introduce rich
  konoha/api/server.py
  poetry.lock
  pyproject.toml
Labels: other

#144 Remove postag information from `__repr__`
  konoha/data/token.py
Labels: core feature

#145 Cleanup codebase
  README.md
  konoha/integrations/allennlp.py
  konoha/word_tokenizer.py
  konoha/word_tokenizers/mecab_tokenizer.py
  tests/integrations/test_allennlp_integration.py
Labels: other

#146 Upgrade mypy
  poetry.lock
  pyproject.toml
Labels: other

#147 Use async methods to avoid resource competition
  konoha/api/v1/batch_tokenization.py
  konoha/api/v1/tokenization.py
Labels: api

#149 Skip tests using AWS credential when it is not provided
  .github/workflows/ci.yml
  tests/api/v1/test_batch_tokenization.py
  tests/api/v1/test_tokenization.py
  tests/test_word_tokenizer.py
Labels: other
